In [3]:
import numpy as np
B = np.arange(3)
print(B)
#print np.exp(B)
print(np.sqrt(B))

[0 1 2]
[0.         1.         1.41421356]


In [4]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))
#print a

#a.shape
## flatten the array
#print a.ravel()
#a.shape = (6, 2)
#print a 
#print a.T
print(a.resize((2,6)))
print(a)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)

None
[[0. 1. 8. 0. 3. 7.]
 [6. 4. 3. 4. 0. 5.]]


In [6]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('---')
print(b)
print('---')
print(np.hstack((a,b)))
#np.hstack((a,b))

[[7. 7.]
 [3. 1.]]
---
[[4. 4.]
 [8. 4.]]
---
[[7. 7. 4. 4.]
 [3. 1. 8. 4.]]


In [7]:
a = np.floor(10*np.random.random((2,12)))
#print a
#print np.hsplit(a,3)
#print np.hsplit(a,(3,4))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print(a)
np.vsplit(a,3)

[[5. 0.]
 [2. 0.]
 [1. 8.]
 [2. 0.]
 [4. 7.]
 [1. 6.]
 [9. 8.]
 [8. 9.]
 [6. 0.]
 [7. 2.]
 [2. 2.]
 [2. 9.]]


[array([[5., 0.],
        [2., 0.],
        [1., 8.],
        [2., 0.]]), array([[4., 7.],
        [1., 6.],
        [9., 8.],
        [8., 9.]]), array([[6., 0.],
        [7., 2.],
        [2., 2.],
        [2., 9.]])]

In [10]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
b is a
b.shape = 3,4
print(a.shape)
print(id(a))
print(id(b))

(3, 4)
2359246791504
2359246791504


In [12]:
#The view method creates a new array object that looks at the same data.
c = a.view()
c is a
c.shape = 2,6
#print a.shape
c[0,4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [11]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
d is a
d[0,0] = 9999
print(d) 
print(a)

[[9999    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
